all: compile
	@echo -e '[INFO] Done!'
clean:
	@echo -e '[INFO] Cleaning Up..'	
	@-rm -rf cs555/**/**/*.class

compile: 
	@echo -e '[INFO] Compiling the Source..'
	@javac -d . cs555/**/**/*.java
	
	
